image: node:6

pages:
  cache:
    paths:
    - node_modules/
  stage: deploy
  script:
  - npm install --only=production
  - npm run-script build:prod
  - mkdir .public
  - cp -r dist/* .public/.
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
